server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.128:3306/guli_wms
    password: root
    username: root

  redis:
    host: 192.168.150.128:3306
mybatis-plus:
  type-aliases-package: com.atguigu.gmall.wms.entity
  mapper-locations: classpath:mapper/wms/**/*.xml
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true
